# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Voices of JupyterHub
author: Organizational Mycology
copyright: 2025
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex
  latex_documents:
    targetname: voicesofjupyterhub2025.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/orgmycology/vojhreport  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <div style="overflow: auto;"> 
    <a href="https://orgmycology.com"><img src="https://data.orgmycology.com/short_logo.svg" style="background-color: white; width: 300px;"></a>
    <p>A Creative Commons Zero Resource</p>
    </div>

